/*
 *  ___  ___   _      ___                 _    
 * |   \/ __| /_\    / __|___ _ _  ___ __(_)___
 * | |) \__ \/ _ \  | (_ / -_) ' \/ -_|_-< (_-<
 * |___/|___/_/ \_\  \___\___|_||_\___/__/_/__/
 *
 * -----------------------------------------------------------------------------
 * @author: Herbert Veitengruber 
 * @version: 1.0.0
 * -----------------------------------------------------------------------------
 *
 * Copyright (c) 2013 Herbert Veitengruber 
 *
 * Licensed under the MIT license:
 * http://www.opensource.org/licenses/mit-license.php
 */
package dsagenesis.core.model;

import dsagenesis.core.model.sql.AbstractSQLRowModel;
import dsagenesis.core.model.xml.AbstractXMLModel;

/**
 * AbstractGenesisModel.
 * 
 * Abstract base class for all Genesis model classes.
 * used by Meta Data editor and Hero Editor
 * to link the SQL models with the XML Models
 */
public abstract class AbstractGenesisModel
{

	/**
	 * getID
	 * 
	 * each object has an ID.
	 * The ID comes from the DB and is stored in Meta Data or Hero Data.
	 *
	 * the ID is generated by an prefix and an numeric value or unique string.
	 * @see TableIndexFactory
	 *  
	 * @return
	 */
	public abstract String getID();
	
	/**
	 * 
	 * @return
	 */
	public abstract AbstractSQLRowModel getSQLRowModel();
	
	/**
	 * 
	 * @return
	 */
	public abstract AbstractXMLModel getXMLModel();
	
}
