/*
 *  __  __      
 * /\ \/\ \  __________   
 * \ \ \_\ \/_______  /\   
 *  \ \  _  \  ____/ / /  
 *   \ \_\ \_\ \ \/ / / 
 *    \/_/\/_/\ \ \/ /  
 *             \ \  /
 *              \_\/
 *
 * -----------------------------------------------------------------------------
 * @author: Herbert Veitengruber 
 * @version: 1.0.0
 * -----------------------------------------------------------------------------
 *
 * Copyright (c) 2013 Herbert Veitengruber 
 *
 * Licensed under the MIT license:
 * http://www.opensource.org/licenses/mit-license.php
 */
package dsagenesis.core.model;

import dsagenesis.core.model.sql.AbstractSQLRowModel;
import dsagenesis.core.model.xml.AbstractXMLModel;

/**
 * IGenesisModel.
 * 
 * base interface for all Genesis model classes.
 * 
 * 
 */
public interface IGenesisModel
{

	/**
	 * getID
	 * 
	 * each object has an ID.
	 * The ID comes from the DB and is stored in Meta Data or Hero Data.
	 *
	 * the ID is generated by an prefix and an numeric value or unique string.
	 * @see TableIndexFactory
	 *  
	 * @return
	 */
	public String getID();
	
	/**
	 * 
	 * @return
	 */
	public AbstractSQLRowModel getSQLRowModel();
	
	/**
	 * 
	 * @return
	 */
	public AbstractXMLModel getXMLModel();
	
}
